CREATE DATABASE blog;
USE blog;

CREATE TABLE USER (
	user_id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    first_name NVARCHAR(255) NOT NULL,
    last_name NVARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    address NVARCHAR(255) NOT NULL,
    role INT DEFAULT 0,
    status INT DEFAULT 1 
);

CREATE TABLE CATEGORY (
	category_id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    name NVARCHAR(50)
);

CREATE TABLE POST (
	post_id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    title NVARCHAR(255) NOT NULL,
    content NVARCHAR(10000) NOT NULL,
    created_at DATE,
    category_id INT NOT NULL,
    user_id INT NOT NULL
);
ALTER TABLE POST ADD CONSTRAINT FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id);
ALTER TABLE POST ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES USER(user_id);

CREATE TABLE REACTION (
	user_id INT NOT NULL,
    post_id INT NOT NULL,
    status INT DEFAULT 0,
    PRIMARY KEY(user_id, post_id)
);

CREATE TABLE REPORT (
	user_id INT NOT NULL,
    post_id INT NOT NULL,
    content NVARCHAR(255),
    created_at DATETIME,
    PRIMARY KEY(user_id, post_id)
);

CREATE TABLE COMMENT (
	comment_id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    content NVARCHAR(500) NOT NULL,
    created_at DATETIME,
    user_id INT NOT NULL,
    post_id INT NOT NULL
);
ALTER TABLE COMMENT ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES USER(user_id);
ALTER TABLE COMMENT ADD CONSTRAINT FOREIGN KEY (post_id) REFERENCES POST(post_id);

CREATE TABLE SUB_COMMENT (
	sub_comment_id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    content NVARCHAR(500) NOT NULL,
    level INT,
    created_at DATETIME,
    user_id INT NOT NULL,
    comment_id INT NOT NULL,
    parent_sub_comment_id INT NOT NULL
); 
ALTER TABLE SUB_COMMENT ADD CONSTRAINT FOREIGN KEY (comment_id) REFERENCES COMMENT(comment_id);
ALTER TABLE SUB_COMMENT ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES USER(user_id);
ALTER TABLE SUB_COMMENT ADD CONSTRAINT FOREIGN KEY (parent_sub_comment_id) REFERENCES SUB_COMMENT(sub_comment_id);

